services:

  db:
    image: mysql:8.4
    container_name: nexacart-db

    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ecommerce

    ports:
      - "3307:3306"

    volumes:
      - nexacart-mysql-data:/var/lib/mysql

    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "-p${MYSQL_ROOT_PASSWORD}"
        ]
      interval: 5s
      timeout: 5s
      retries: 10


  app:
    build: .
    container_name: nexacart-app

    ports:
      - "8080:8080"

    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}

    depends_on:
      db:
        condition: service_healthy


volumes:
  nexacart-mysql-data: